# -*- coding: utf-8 -*-
"""Part C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzKgs51P1XXGGWIxlzASh8-V-D0GD_wd

Q1 — Difference Between elif and Multiple if?
Ans- If condition -It stops after first true condition.
elif condition- It checks all condition
"""

number = 15

if number > 10:
    print("Greater than 10")

if number > 5:
    print("Greater than 5")

number = 15
if number > 10:
    print("Greater than 10")

elif number > 5:
    print("Greater than 5")

"""Q2: Coding"""

def classify_triangle(a, b, c):

    if a <= 0 or b <= 0 or c <= 0:
        return "Invalid: sides must be positive"

    if a + b <= c or a + c <= b or b + c <= a:
        return "Not a triangle"

    if a == b == c:
        return "Equilateral"

    elif a == b or b == c or a == c:
        return "Isosceles"

    else:
        return "Scalene"

print(classify_triangle(5,5,5))

"""Q3 — Debugging Question"""

score = 85

if score >= 60:
    grade = 'D'
if score >= 70:
    grade = 'C'
if score >= 80:
    grade = 'B'
if score >= 90:
    grade = 'A'

print(grade)

"""The program uses multiple if statements instead of elif, so each condition overwrites the previous grade."""

score = 85

if score >= 90:
    grade = 'A'

elif score >= 80:
    grade = 'B'

elif score >= 70:
    grade = 'C'

elif score >= 60:
    grade = 'D'

else:
    grade = 'F'

print(grade)

"""Even though grading logic is unclear and inefficient."""