# -*- coding: utf-8 -*-
"""Part D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzKgs51P1XXGGWIxlzASh8-V-D0GD_wd

Write a Python program that validates an Indian PAN card number format using if-else conditions.

PAN format rules:
- 5 uppercase letters
- 4 digits
- 1 uppercase letter

Example: ABCDE1234F
The 4th character indicates the taxpayer type.
"""

pan = input("Enter PAN number: ")

if len(pan) == 10:

    if pan[:5].isalpha() and pan[:5].isupper():

        if pan[5:9].isdigit():

            if pan[9].isalpha() and pan[9].isupper():
                print("Valid PAN")

            else:
                print("Invalid PAN")

        else:
            print("Invalid PAN")

    else:
        print("Invalid PAN")

else:
    print("Invalid PAN")

"""Correct Aspects--
Length validation
Letter/digit structure checked
Uppercase letters enforced
"""